apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-fiap.fullname" . }}-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.repository }}:{{ .Values.app.tag }}
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: {{  .Values.app.name }}-config
          ports:
            - name: http
              containerPort: {{ .Values.service.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: {{ .Values.service.app.targetPort }}
          readinessProbe:
            httpGet:
              path: /api
              port: {{ .Values.service.app.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
