apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-fiap.name" . }}-svc
  labels:
    {{- include "k8s-fiap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-fiap.selectorLabels" . | nindent 4 }}
