apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
      nodePort: {{ .Values.service.app.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
