# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: default
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
  - name: {{ .Values.db.name }}
    protocol: TCP
    port: 3306
    targetPort: 3306
---
