# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.name }}-sts
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  serviceName: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - name: {{ .Values.db.name }}
        image: {{ .Values.db.repository }}:{{ .Values.db.tag }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.name }}-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.name }}-secret
                key: MYSQL_PASSWORD
        envFrom:
          - configMapRef:
              name: {{ .Values.db.name }}-config
        ports:
        - containerPort: 3306
          name: {{ .Values.db.name }}
        volumeMounts:
        - name: {{ .Values.db.name }}-persistent-storage
          mountPath: {{ .Values.db.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.db.name }}-persistent-storage
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---

