apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "k8s-fiap.name" . }}-pv
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/thiagoflins/projects/personal/fiap/k8s-fiap/db_data"
