apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "k8s-fiap.name" . }}-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
